### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#108]
As an editor (or reader) I need to be able to export transcriptions in a variety of formats (xml, pdf, .doc, epub etc.)

**Comment by AnnaGerber** [comment]
I've added PDF export in https://github.com/uq-eresearch/austese_repository/commit/edec4394f73d2e8a15f4e637ea121c1bb25f5c44. Is this enough for now or do we need ePub as well?

**Comment by AnnaGerber** [comment]
Closing as PDF and Word are supported - other formats may be added later
