### ISSUE TITLE
Graphical Editor for Artefact Relationships

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#112]
As an editor, I would like to graphically map and store relationships between artefacts. 

This should also include 'events' and related roles that produce the material artefacts.

This supports the manual creation of a stemma to show the paths of textual transmission. 

The stemma can be revised or locked, providing a an opportunity to model the relationships before during and after editing.

**Comment by AnnaGerber** [comment]
Relationships can be visualised but not edited graphically. Graphical editor is out of scope for current project (may be reopened later)
