### ISSUE TITLE
Subscribing to Annotations

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#117]
As a reader, I need to be able to subscribe to an RSS feed that alerts me to new annotations at Work, Version, or Artefact level.

**Comment by AnnaGerber** [comment]
Atom feeds available for annotation search by creator, target or search terms (e.g. keyword, tag etc). Subscribe links supplied via search UI. Implemented in https://github.com/uq-eresearch/austese_annotations/commit/0260482c1cb7cbf0d8bfb46d86719db1936f4c24
