### ISSUE TITLE
Specify rights and access

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/AustESE#12]
As an editor I would like to specify who has permission to view and update digital resources.

**Comment by tomcollinsandcompany** [comment]
Rights can be specified in Digital Resource Editor.

Editing and viewing acces privileges are active in Drupal, but currently restricted. This operation will be extended to users in 2013 when workflow engine is completed.

**Comment by AnnaGerber** [comment]
Covered by project based permissions
