### ISSUE TITLE
Duplicate Digital Object (Transcription)

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#135]
As an editor, I need to be able to duplicate a transcription in order to edit that duplicate and critically establish a new reading text.

**Comment by AnnaGerber** [comment]
Also for bibliographic entities (e.g. versions, artefacts, works etc) to reduce data entry time

**Comment by AnnaGerber** [comment]
This has been implemented although currently the metadata is not duplicated - only the resource content - not sure whether it should be
