### ISSUE TITLE
Advanced Annotation Search Enhancements

### ISSUE THREAD

**Issue by omad** [uq-eresearch/AustESE#138]
**Reported by BDH**
- Searching of annotations – limit keyword search by motivation/user/date
- Searching of annotations – problematic keywords also used as motivation descriptors (e.g. searching for “note”, “annotation”, etc…)

Practical question: how granular are the searches? (Issue of returning results for annotations associated with characters on either side of the target used for locate the target in context)

**Comment by AnnaGerber** [comment]
After discussion with @RogerOsborne , added keyword search within bodies only https://github.com/uq-eresearch/austese_annotations/commit/74d86ba081aea7e1fd47d706596b857ff0f01412
