### ISSUE TITLE
Combined Editing Interface

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#149]
When creating new Work, Version, Artefact records, it would be useful to have a combined editing interface, particularly when dealing with many Parts and Fragments. See Nostromo: http://austese.net/repository/works/51ec7ef01b2632b337000000. 

I'm thinking of the AustLit editing interface (see below) Where Works/Expressions/Manifestations are all presented on the one form. At VERSION level, Parts could be added by clicking a + sign and adding a short name. The transcription field and artefact field would allow for efficient addition or creation of artefacts and images.

Sketch to follow. 

![image](https://f.cloud.github.com/assets/1567062/839658/2b866998-f351-11e2-85b1-f277c393596b.png)

**Comment by AnnaGerber** [comment]
After discussion, we are going to trial keeping the editing forms separate, but adding buttons to create new versions etc at the point where they are linked (which open the form to create the new entities in a new tab)
