### ISSUE TITLE
Creative Commons Licence

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#151]
Editors need to be able to easily attach appropriate Creative Commons Licence to digital objects, single and batch.

**Comment by AnnaGerber** [comment]
The recommended way to do this in RDF is using cc:license property http://creativecommons.org/ns#

e.g. 
&lt;cc:license rdf:resource="http://creativecommons.org/licenses/by/1.0/"/&gt;

**Comment by AnnaGerber** [comment]
Also  arbitrary copyright or license information for digital resources

**Comment by AnnaGerber** [comment]
At the moment this can be achieved by editing dc:rights property (batch or single) in resource organiser
