### ISSUE TITLE
Implement AAF authentication

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/AustESE#152]
This is a requirement from the original project proposal. AAF (Shibboleth) auth should be provided in addition to the existing open id based auth.

This drupal module looks like the best candidate:
https://drupal.org/project/shib_auth

**Comment by AnnaGerber** [comment]
Steps according to this post http://support.rc.nectar.org.au/forum/viewtopic.php?f=3&t=254
1. Set up Service Provider http://wiki.aaf.edu.au/tech-info/sp-install-guide
2. Integrate with software (e.g. drupal module as above)

**Comment by omad** [comment]
I've started work on this by requesting the AustESE Test server be added to the Test AAF Federation. This is still pending.

Use of the Production AAF requires HTTPS to be used on our server. I've generated a certificate request and sent it to ITS for a certified *.austese.net certificate.
