### ISSUE TITLE
Warning for Invalid XML before MVD created

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#154]
An editor needs to be warned about invalid xml. Currently, MVD provides a log report about invalid xml after an MVD is created. Could this warning come up before files are SENT to MVD?

**Comment by AnnaGerber** [comment]
Yes, the results of attempting to parse the file could displayed on the resource page.
Would error highlighting (e.g. mismatched tags) in the editor also help?

**Comment by tomcollinsandcompany** [comment]
Yes, dealing with this in the workflow (text editor step) would solve the issue. But also good to get an early warning from MVD instead of a later one if possible.

Dr Roger Osborne
http://furphyarchive.wordpress.com/

AustESE Projecthttp://itee.uq.edu.au/%7Eeresearch/projects/austese/index.html
eResearch Grouphttp://itee.uq.edu.au/%7Eeresearch
School of Information Technology and Electrical Engineering (ITEE)
The University of Queensland
St Lucia QLD Australia 4072
