### ISSUE TITLE
Remove digital resource

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/AustESE#16]
As project leader I would like to remove digital resources attached to a project.

**Comment by tomcollinsandcompany** [comment]
Digital resources can be deleted.

Specified role that restrict acces to such actions is yet to be implemented.

**Comment by AnnaGerber** [comment]
Closing this as resources can be removed - roles allowed to delete resources are covered by user story #12

**Comment by AnnaGerber** [comment]
UI test demonstrating this feature:
https://saucelabs.com/tests/4031f3711f7140fdbb5dccc761dba879
