### ISSUE TITLE
Preview transcriptions while editing

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/AustESE#161]
As an editor I need to preview TEI transcriptions while I am editing to see how they will be rendered and ensure they are valid

**Comment by AnnaGerber** [comment]
Manual test session testing editor and transformation to HTML
https://saucelabs.com/tests/4aa454ca67d14e409b78a18b101bc4a0

**Comment by tomcollinsandcompany** [comment]
Could the Transcription Preview be framed separately in order to have scrolling independent of the page? Previewing minor corrections at the bottom of a long page currently scrolls the user away from the Editor, requiring another scroll to return.

**Comment by AnnaGerber** [comment]
After discussion: suggested enhancement is to add a floating button/link to go back to the editor rather than restricting the size of the preview and adding scrollbar
