### ISSUE TITLE
Formatting Annotations

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#163]
As an editor/reader, I need a simple formatting toolbar to write annotations (eg bold italics, bullets, indent, colours)

**Comment by tomcollinsandcompany** [comment]
Annotation editor needs refinement so that ENTER = carriage return when in editing mode. Currently, ENTER = save. That is, something is needed to create paragraphs, and Enter is the usual method for novices.

**Comment by AnnaGerber** [comment]
Enter markdown directly in the annotation editor to support basic formatting e.g. headings, bullets, italics, bold, links etc.
See http://daringfireball.net/projects/markdown/syntax for markdown syntax
Note that not all markdown syntax is supported (only the basics)

**Comment by tomcollinsandcompany** [comment]
Testing MarkDown in annotations:

Is it possible to make links within an annotation open in a new Tab?

Currently they open in the same Tab, and in the case of an MVD in the Reading View within that frame.

Can the default font style in the annotation editor be rendered plain, not in italics?

Is there a code that indents? In annotations, > angle brackets don't render as indented block quotes.

All else seems ok as a simple formatting option.

**Comment by tomcollinsandcompany** [comment]
Ok, learned some more markdown. Double-space at end-of-line creates a line break, allowing you to do this:

this:  

> this  
> this  

this  

That's fine, but I'll add a MarkDown guide to the User Manual. Unless there is other advice??

BUT, Annotator doesn't seem to render as above, leaving the angle brackets.

See http://austese.net/annotations/search/id?uri=http%3A%2F%2Faustese.net%2Florestore%2Foa%2FBC29D7C62B81D2AD

**Comment by AnnaGerber** [comment]
The editor and annotation popup should be rendering in normal (non-italic) text.

Markdown doesn't support links opening in new tabs but I can make that the default behaviour for all links in annotations

I'll look into why the blockquotes aren't rendering in the annotator popup

**Comment by AnnaGerber** [comment]
Blockquotes should be rendering properly now. A side effect of making blockquotes work is that you can now use HTML directly if you need more control over colours, indentation etc.

**Comment by AnnaGerber** [comment]
Formatting enabled. Created a new issue for the links in new tabs: #233
