### ISSUE TITLE
Creating Situations

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#172]
I need to be able to create Situations to provide temporal contexts for Events. For example, Joseph Furphy's visit to Sydney in April 1901 is a Situation that had a significant effect on his revision of the 1898 typescript. But other Situations such as Federation, World Wars etc. can be recorded in this way. These can be rendered on a timeline as distinct from Artefact-producing Events.

**Comment by AnnaGerber** [comment]
Events have both a type and a tag - this should be sufficient for distinguishing situations
