### ISSUE TITLE
Visualise bibliographic and artefact relationships

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/AustESE#19]
As an editor or reader I would like to visualise relationships between  artefacts and fragments of artefacts.

**Comment by tomcollinsandcompany** [comment]
Jesse Claven, Summer Research Scholar, is developing a number of visualisations that will displays such relationships as networks and graphs. Top be completed end of January 2013.

**Comment by AnnaGerber** [comment]
UI test demonstrating this feature:
https://saucelabs.com/tests/93c7203975da4745af225c0dc497232c
