### ISSUE TITLE
MVD Versions should use Version name not File name

### ISSUE THREAD

**Issue by omad** [uq-eresearch/AustESE#201]
When viewing an MVD, the drop down menus should use the metadata version name, instead of the file name.

It is confusing to have to select the file name.

**Comment by AnnaGerber** [comment]
Names from Calliope are used - so whatever short name of the transcription was sent (defaults to filename if no short name set) plus layers generated by MVD. Can't be tied to versions as diplomatic transcriptions can also be sent to MVD (or transcriptions during editing phase before metadata for artefacts, versions is created).
