### ISSUE TITLE
Deleting Version Leaves Orphan (Reading View Doesn't Work)

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#222]
I deleted a Version, deciding that it was not a distinct version. However, a dot point remains on the work, and the Reading View no longer loads transcriptions. All related?

http://austese.net/repository/works/501f558adf8ede3655000000?project=22

The version deleted was Such is Life (American Edition).

**Comment by AnnaGerber** [comment]
Same problem as #203, #202 - closing duplicate issue
