### ISSUE TITLE
Agent Roles Displayed in Events

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#223]
Instead of eg "1 Author participated in this event", Could the RoleName be displayed instead. That is, produce a list that states:

Author
Publisher
Editor
Illustrator
etc.

**Comment by AnnaGerber** [comment]
Do you mean list each agent and then their roles after their name? Or add role headings to the existing list?

**Comment by tomcollinsandcompany** [comment]
http://austese.net/repository/events/520422851b2632055b000007?project=24

It's a formatting idea to simplify the Event record only. For the example above, read

Author + Joseph Conrad
Publisher + J. M. Dent

Instead of 

1 author participated in this event
     + Joseph Conrad

1 publisher participated in this event
    + J. M. Dent

But, let me know if you think this reduces clarity, or whether there are other implications. Probably influenced by AustLit records.
