### ISSUE TITLE
Fix sort by title for Works

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/AustESE#251]
Currently not sorting alphabetically
Should sort ignoring articles e.g. "a" and "the"

**Comment by AnnaGerber** [comment]
Default sort should be alphabetic

**Comment by omad** [comment]
Results are now sorted by their filterfield, which should display them alphabetically. They're sorted by elasticsearch which is ignoring articles.

Fixed in uq-eresearch/austese_repository@9e8875ed15f3a0e7f927008c5688718d7fd69c26
