### ISSUE TITLE
Sorting the MVD list

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#278]
Is there a way to make the MVD list more sortable?

Currently, the newest MVD appears at the head of the list. When you've got so many that the list starts paging, then it's difficult to check through chapter by chapter, especially when returning to the MVD list resets to the beginning.

Could Compare and Table open in a new Tab to get around this?? Or are there other solutions?

**Comment by AnnaGerber** [comment]
Yes, not a problem.
In the meantime you can open the compare or table links in a new tab by clicking the link with the middle mouse button or control-click > open link in new tab

**Comment by tomcollinsandcompany** [comment]
Ah, yes, control-click> works nicely in the interim.
