### ISSUE TITLE
Reading View not Working for Such is Life

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#281]
Reading View for the Work Such is Life is not working at this time:

http://austese.net/reading/501f558adf8ede3655000000?project=22

Recent changes included the upload of 400 images and the creation of ArtefactParts.

**Comment by omad** [comment]
There was some debugging code resulting in an oversized request header, that was preventing the complete work record from making it through the UQ Proxy.

Fixed in uq-eresearch/austese_repository@c2e017b1b2362d0923367f6c68a797dd09544b86
