### ISSUE TITLE
Deleting Annotation Fails

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#297]
In addition to other annotation deletion failures, this annotation also cannot be deleted: http://austese.net/annotations/search/id?uri=http%3A%2F%2Faustese.net%2Florestore%2Foa%2F5EC543FE9F1BB63D

**Comment by AnnaGerber** [comment]
Annotations are deleting for me (including this one). 
Please re-open this issue if the problem occurs again, and if it does please report any associated errors (e.g. if you right-click on the page and 'Inspect Element' in Chrome, and look for errors displayed in red in the Console).
