### ISSUE TITLE
Reading View Slow to Load

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#299]
When large numbers of images are associated with an Artefact, the Reading View still takes much too long to load.

**Comment by omad** [comment]
Can you please include a link to a large example I can test with

**Comment by tomcollinsandcompany** [comment]
Both Such is Life and Nostromo reading views are slow to load, Nostromo especially. 

Here is Such is Life: http://austese.net/reading/501f558adf8ede3655000000?project=22

Here is Nostromo: http://austese.net/reading/51ec7ef01b2632b337000000?project=24

**Comment by omad** [comment]
This should be much better now.

It's not as fast as I would like, but I've run out of time to work on it. The reading view in general needs a good working over now that there's _real_ data.

**Comment by tomcollinsandcompany** [comment]
Yes, much better. Thanks.
