### ISSUE TITLE
Chronology and Timeline

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#303]
1. Chronology currently not displaying in Furphy Project: "Found null events,  displaying page 1 of NaN"
2. Chronology not displaying in date order.
3. Not all events are displayed on Furphy Project timeline, but they do appear on Chronology (when it is working).
4. Furphy Project will probably favour the Chronology format, rather than timeline.

**Comment by tomcollinsandcompany** [comment]
Actually, problem number 1 also occurs for works, agents, versions.

**Comment by omad** [comment]
These should all be fixed now.

This will also fix a problem that was causing records to not be sorted correctly.

The wrong ElasticSearch mapping was in use for the code update this morning, it needed to be cleaned out and fixed.
