### ISSUE TITLE
Edit transcription

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/AustESE#32]
As an editor I need to edit and mark-up transcriptions and have them transformed.

**Comment by tomcollinsandcompany** [comment]
See Digital Resource Editor in Sandbox: http://austese.net/repository/resources

Double click on text resources opens in simple editor.

**Comment by AnnaGerber** [comment]
Manual test session testing editor and transformation to HTML
https://saucelabs.com/tests/4aa454ca67d14e409b78a18b101bc4a0
