### ISSUE TITLE
Describe transcriptions

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/AustESE#33]
As an editor I need to describe transcriptions and link them with bibliographic records.

**Comment by tomcollinsandcompany** [comment]
Metadata can be added in Digital Resource Editor.

Linking to bibliographic records via Digital Resource Editor will be implemented in earl 2013

**Comment by tomcollinsandcompany** [comment]
Links between bibliographic records and digital resources is currently done in Content Repository demonstrator. See http://austese.net/repository
