### ISSUE TITLE
Visualise variants

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/AustESE#43]
As an editor I would like to analyse and visualise the concentration of specified types of variation.

**Comment by tomcollinsandcompany** [comment]
Jesse Claven, Summer Research Scholar, is developing such visualising by drawing on MVD data. To be completed in January 2013.

**Comment by AnnaGerber** [comment]
Currently provided via comparison and table view (other visualisations out of scope for remainder of project)
