### ISSUE TITLE
Filter annotations by type

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/AustESE#50]
As an editor, I would like to view a list of specified ‘types’ of annotations (e.g. list all annotations that identify and discuss typist errors).

**Comment by tomcollinsandcompany** [comment]
Viewing annotations at any point where a text or image can be viewed (ie resource record, MVD views) is essential. And so a drop down menu in the sidebar that says something like "view annotations" with the next option "view by type, tag" etc. will be very helpful.

**Comment by AnnaGerber** [comment]
Use freeform tags to identify these types of annotations. See #132
