### ISSUE TITLE
Copy edit / upload corrections

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/AustESE#64]
As a copy-editor I would like to provide corrections.

**Comment by AnnaGerber** [comment]
Is being able to provide corrections via the transcription editor sufficient or does this need to be enabled via other means e.g. uploading an entirely new version of a file, or via annotations?

**Comment by tomcollinsandcompany** [comment]
I think corrections will be input into the transcription editor, but copy-editing might be done on both screen and/or paper, depending on the copy-editor's preferences. This is now a question more about output. If a transcription file can be printed, then that is all that needs to be done. Corrections will be transferred from the marked up page to new version via the transcription editor. If archiving is necessary, the marked up copy could be scanned and uploaded to the repository.

**Comment by AnnaGerber** [comment]
OK. Closing this issue then, as editing is covered by #32, printing is covered by #75, uploading images by #23 , and tagging as proof/corrections is covered by #162
