### ISSUE TITLE
Add collaborators

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/AustESE#7]
As project leader, I would like to invite editors to collaborate on the project.

**Comment by AnnaGerber** [comment]
Could be enabled via existing drupal modules e.g. http://drupal.org/project/invite

**Comment by omad** [comment]
Enabled using http://drupal.org/project/og_invite module. It allows entering a list of email addresses to invite to a project. User accounts are created and an email is sent to each user, with a one time use login link for them to change their password.

They can be assigned roles and permissions immediately by the project manager.

**Comment by AnnaGerber** [comment]
Related to #22 #63 #28
