### ISSUE TITLE
Annotate (Annotation Types)

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/AustESE#70]
As a registered user of the workbench, I would like to annotate content (e.g. transcriptions, facsimiles) from any edition with comments and notes.

**Comment by tomcollinsandcompany** [comment]
Annotations such as these need to be of several types: Explanatory Note; Textual Note; Comment; Question. Explanatory Notes and Textual Notes are probably best assigned to Editors and Comments and Questions to Readers.

**Comment by AnnaGerber** [comment]
Implemented in AustESE Annotator Motivations plugin
See https://github.com/uq-eresearch/annotator/commit/71461f2906092a2887d088d81a5eb0661ae6bb34
