### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#94]
As a reader I need to be able to cite annotations as references in my scholarly essay.

**Comment by ghost** [comment]
This is possible as all annotations have a URI

**Comment by AnnaGerber** [comment]
The share icon provided by the search UI makes citing annotations easier as it makes it easier to copy the URI for any annotation. Added in https://github.com/uq-eresearch/austese_annotations/commit/5b0e2efa89da891e9de70369ed1049be8209727e
