### ISSUE TITLE
Grouping Annotations

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#95]
As an editor (or reader) I need to group annotations in order to create 'revision narratives'.

**Comment by tomcollinsandcompany** [comment]
There has been some discusion with steering committee members about conceptualising a publication space (ie like a journal) where commentaries of various lengths can be published, perhaps under peer review conditions. Grouped annotations (from within editions and across editions) could be one way of doing this.

**Comment by AnnaGerber** [comment]
Annotations can be grouped by tagging
